#!/bin/bash
file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

case "$ext" in
	# keep alphabetical order
	c) 		gcc "$file" -o "$base" && "$base" ;;
	cc) 	g++ "$file" -o "$base" && "$base" ;;
	cpp) 	g++ "$file" -o "$base" && "$base" ;;
	java) 	javac -d classes "$file" && java -cp classes "${1%.*}" ;;
	md)		pandoc "$file" -o "$base".pdf ;;
	rs) 	cargo build ;;
	tex) 	pdflatex "$file";;
	default) exit ;;
esac
